version: 2

project_name: eidos

builds:
  - binary: eidos
    # set the modified timestamp on the output binary to the git timestamp to ensure a reproducible build
    mod_timestamp: &build-timestamp '{{ .CommitTimestamp }}'
    dir: .
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    flags:
      - -trimpath
    ldflags: &build-ldflags |
      -w
      -s
      -extldflags "-static"
      -X github.com/NVIDIA/cloud-native-stack/cli/cmd.version={{.Version}}
      -X github.com/NVIDIA/cloud-native-stack/cli/cmd.commit={{.ShortCommit}}
      -X github.com/NVIDIA/cloud-native-stack/cli/cmd.date={{.Date}}
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

universal_binaries:
  - name_template: "eidos"
    replace: false  # keep platform-specific binaries too

gomod:
  proxy: false

sboms:
  - artifacts: binary

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
  algorithm: sha256

snapshot:
  version_template: "{{ .Tag }}-next"

report_sizes: true

metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"

release:
  github:
    owner: NVIDIA
    name: cloud-native-stack
  prerelease: auto

kos:
  - base_image: cgr.dev/chainguard/static
    platforms:
      - linux/amd64
      - linux/arm64
    tags:
      - latest
      - "{{.Tag}}"
    preserve_import_paths: false
    bare: true
    sbom: spdx

archives:
  - id: eidos
    formats:
      - binary
    name_template: "{{ .Binary }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^lint:"
      - "^chore: readme"
      - "^chore: bump version"
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Tasks"
      regexp: '^.*?chore(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "Bug fixes"
      regexp: '^.*?bug(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999
